image: alpine/edge
packages:
  - python3
  - py3-pip
  - uv
  - make
  - hut
sources:
  - https://git.sr.ht/~hxii/boku
artifacts:
  - dist/*.whl
tasks:
  - setup: |
      cd boku
      uv venv
      uv sync --dev
  - lint: |
      cd boku
      make check
    # NOTE: Disabling tests until I can write proper ones
  # - test: |
  #     cd boku
  #     make test
  - build: |
      cd boku
      make build
  - release: |
      cd boku
      if [[ "$GIT_REF" == refs/tags/* ]]; then
        TAG=${GIT_REF#refs/tags/}
        if [[ -n "$TAG" ]]; then
          echo "Build triggered by tag: $TAG"
          hut git create-release \
            --tag "$TAG" \
            --title "Boku $TAG" \
            --files dist/*.whl \
            git.sr.ht/~hxii/boku
        else
          echo "Error: Empty tag name extracted from GIT_REF: $GIT_REF"
        fi
      else
        echo "Build not triggered by a tag. Skipping release."
        echo "GIT_REF: $GIT_REF"
      fi
secrets:
  - 4182e030-48da-4ad4-b8b6-a6b61445475b
triggers:
  - action: email
    condition: always
    to: hxii+builds@0xff.nu
